hyperparameters: 
  TEST_VALIDATION_SPLIT: 0.2
  VALIDATION_SPLIT: 0.5
  BATCH_SIZE: 32 
  NUM_WORKERS: 0
  NUM_EPOCHS: 5
  LR: 0.001
model_information: 
  model_name: BARTSmiles
dataset_information: 
  dataset: data/processed/smiles_dataset.csv