hyperparameters: 
  TEST_VALIDATION_SPLIT: 0.2
  VALIDATION_SPLIT: 0.5
  BATCH_SIZE: 32 
  NUM_WORKERS: 0
  NUM_EPOCHS: 40
  LR: 0.03355827020929843
  NUM_AUGMENTATIONS: 3
model_information: 
  model_name: ChemBERTa-77M-MTR
dataset_information: 
  dataset: data/processed/smiles_dataset.csv
