hyperparameters: 
  VAL_SPLIT: 0.05
  BATCH_SIZE: 32 
  NUM_WORKERS: 0
  PATIENCE: 7
  NUM_EPOCHS: 50
  LR: 0.0000341489300450984
  WEIGHT_DECAY: 0.02813105415629362
  NUM_SPLITS: 5
  BETA1: 0.913565211895004
  BETA2: 0.9826898029990806
  CLASSIFIER_DROPOUT: 0.4970983440156713
  NUM_SPLITS: 20
model_information: 
  model_name: MolFormer-XL
dataset_information: 
  dataset: data/processed/smiles_dataframe.csv