hyperparameters: 
  TEST_SPLIT: 0.2
  BATCH_SIZE: 32 
  NUM_WORKERS: 0
  NUM_EPOCHS: 25
  LR: 0.031039805157262273
  NUM_AUGMENTATIONS: 3
  WEIGHT_DECAY: 0
  NUM_SPLITS: 5
model_information: 
  model_name: MolFormer-XL
dataset_information: 
  dataset: data/processed/smiles_dataset.csv