hyperparameters: 
  TEST_SPLIT: 0.2
  BATCH_SIZE: 32 
  NUM_WORKERS: 0
  NUM_EPOCHS: 15
  LR: 0.031307566143239346
  NUM_AUGMENTATIONS: 3
  WEIGHT_DECAY: 0
  NUM_SPLITS: 5
  BETA1: 0.9 
  BETA2: 0.999
  CLASSIFIER_DROPOUT: 0.1
model_information: 
  model_name: Mol-Gen
dataset_information: 
  dataset: data/processed/selfies_dataset.csv