hyperparameters: 
  VAL_SPLIT: 0.2
  BATCH_SIZE: 32 
  NUM_WORKERS: 0
  PATIENCE: 7
  NUM_EPOCHS: 25
  LR: 0.012610284472465557
  NUM_AUGMENTATIONS: 3
  WEIGHT_DECAY: 0
  NUM_SPLITS: 5
  BETA1: 0.9 
  BETA2: 0.999
  CLASSIFIER_DROPOUT: 0.1
model_information: 
  model_name: SELFIES-TED
dataset_information: 
  dataset: data/processed/selfies_dataframe.csv